### ISSUE TITLE
仅使用/info会报网络错误

### ISSUE THREAD

**Issue by Tsurumaki-Kokoro** [yaowan233/nonebot-plugin-osubot#26]
报文如下：
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 56, in <module>
    nonebot.run()
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\uvicorn\main.py", line 568, in run
    server.run()
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\uvicorn\server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\nonebot_plugin_osubot\__init__.py", line 187, in _info
    data = await draw_info(user, GM[mode])
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\nonebot_plugin_osubot\draw\info.py", line 41, in draw_info
    bg = await get_random_bg()
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\nonebot_plugin_osubot\api.py", line 125, in get_random_bg
    res = await safe_async_get('https://api.gmit.vip/Api/DmImg?format=image')
> File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\nonebot_plugin_osubot\network\auto_retry.py", line 17, in wrapper
    return await func(*args, **kwargs)
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\nonebot_plugin_osubot\api.py", line 28, in safe_async_get
    req = await client.get(url, headers=headers, follow_redirects=True, params=params)
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\httpx\_client.py", line 1754, in get
    return await self.request(
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\UserData\Bots\new osubot\nonebot2-oneclick-win-main\.venv\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed
04-18 10:51:58 [ERROR] nonebot_plugin_osubot | 多次重试失败，请检查网络连接

其他指令均正常工作

**Comment by yaowan233** [comment]
最新版已修复该问题
请将插件版本升级到最新版

**Comment by Tsurumaki-Kokoro** [comment]
已解决
