### ISSUE TITLE
绑定用户异常

### ISSUE THREAD

**Issue by ABKQPO** [yaowan233/nonebot-plugin-osubot#39]
使用/bind ”用户名“ 时出现以下报错11-18 02:45:21 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_osubot.matcher.bind, lineno=21) failed.
Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\tortoise\backends\sqlite\client.py", line 34, in translate_exceptions_
    return await func(self, query, *args)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\tortoise\backends\sqlite\client.py", line 117, in execute_insert
    return (await connection.execute_insert(query, values))[0]
  File "D:\NoneBot\ABK\.venv\lib\site-packages\aiosqlite\core.py", line 194, in execute_insert
    return await self._execute(self._execute_insert, sql, parameters)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "D:\NoneBot\ABK\.venv\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\aiosqlite\core.py", line 74, in _execute_insert
    cursor = self._conn.execute(sql, parameters)
sqlite3.OperationalError: table Info has no column named date

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 201, in run
    uvicorn.run(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run
    await handler(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_osubot\matcher\bind.py", line 37, in _bind
    msg = await bind_user_info("bind", name, event.get_user_id(), True)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_osubot\info\bind.py", line 18, in bind_user_info
    await update_user_info(uid)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_osubot\info\bind.py", line 33, in update_user_info
    await InfoData.create(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\tortoise\models.py", line 1136, in create
    await instance.save(using_db=db, force_create=True)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\tortoise\models.py", line 944, in save
    await executor.execute_insert(self)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\tortoise\backends\base\executor.py", line 227, in execute_insert
    insert_result = await self.db.execute_insert(self.insert_query, values)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\tortoise\backends\sqlite\client.py", line 36, in translate_exceptions_
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: table Info has no column named date

**Comment by mas-alone** [comment]
最简单的话是删除数据库重新生成一份，你应该是旧版更新上来的。

**Comment by yaowan233** [comment]
> 使用/bind ”用户名“ 时出现以下报错11-18 02:45:21 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_osubot.matcher.bind, lineno=21) failed. Traceback (most recent call last): File "D:\NoneBot\ABK.venv\lib\site-packages\tortoise\backends\sqlite\client.py", line 34, in translate_exceptions_ return await func(self, query, *args) File "D:\NoneBot\ABK.venv\lib\site-packages\tortoise\backends\sqlite\client.py", line 117, in execute_insert return (await connection.execute_insert(query, values))[0] File "D:\NoneBot\ABK.venv\lib\site-packages\aiosqlite\core.py", line 194, in execute_insert return await self._execute(self._execute_insert, sql, parameters) File "D:\NoneBot\ABK.venv\lib\site-packages\aiosqlite\core.py", line 129, in _execute return await future File "D:\NoneBot\ABK.venv\lib\site-packages\aiosqlite\core.py", line 102, in run result = function() File "D:\NoneBot\ABK.venv\lib\site-packages\aiosqlite\core.py", line 74, in _execute_insert cursor = self._conn.execute(sql, parameters) sqlite3.OperationalError: table Info has no column named date
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "", line 25, in File "D:\NoneBot\ABK.venv\lib\site-packages\nonebot__init__.py", line 331, in run get_driver().run(*args, **kwargs) File "D:\NoneBot\ABK.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 201, in run uvicorn.run( File "D:\NoneBot\ABK.venv\lib\site-packages\uvicorn\main.py", line 587, in run server.run() File "D:\NoneBot\ABK.venv\lib\site-packages\uvicorn\server.py", line 61, in run return asyncio.run(self.serve(sockets=sockets)) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete self.run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever super().run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever self._run_once() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once handle._run() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run self._context.run(self._callback, *self._args) File "D:\NoneBot\ABK.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher await _run_matcher(
> 
> > File "D:\NoneBot\ABK.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
> > await matcher.run(bot, event, state, stack, dependency_cache)
> > File "D:\NoneBot\ABK.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run
> > await self.simple_run(bot, event, state, stack, dependency_cache)
> > File "D:\NoneBot\ABK.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run
> > await handler(
> > File "D:\NoneBot\ABK.venv\lib\site-packages\nonebot\dependencies__init__.py", line 113, in **call**
> > return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> > File "D:\NoneBot\ABK.venv\lib\site-packages\nonebot_plugin_osubot\matcher\bind.py", line 37, in _bind
> > msg = await bind_user_info("bind", name, event.get_user_id(), True)
> > File "D:\NoneBot\ABK.venv\lib\site-packages\nonebot_plugin_osubot\info\bind.py", line 18, in bind_user_info
> > await update_user_info(uid)
> > File "D:\NoneBot\ABK.venv\lib\site-packages\nonebot_plugin_osubot\info\bind.py", line 33, in update_user_info
> > await InfoData.create(
> > File "D:\NoneBot\ABK.venv\lib\site-packages\tortoise\models.py", line 1136, in create
> > await instance.save(using_db=db, force_create=True)
> > File "D:\NoneBot\ABK.venv\lib\site-packages\tortoise\models.py", line 944, in save
> > await executor.execute_insert(self)
> > File "D:\NoneBot\ABK.venv\lib\site-packages\tortoise\backends\base\executor.py", line 227, in execute_insert
> > insert_result = await self.db.execute_insert(self.insert_query, values)
> > File "D:\NoneBot\ABK.venv\lib\site-packages\tortoise\backends\sqlite\client.py", line 36, in translate_exceptions_
> > raise OperationalError(exc)
> > tortoise.exceptions.OperationalError: table Info has no column named date

把info表删了就行

**Comment by ABKQPO** [comment]
这个文件应该在哪里删除？

**Comment by yaowan233** [comment]
> 这个文件应该在哪里删除？

默认就在bot根目录有个.sqlite文件
