### ISSUE TITLE
更新后无法正常加载插件

### ISSUE THREAD

**Issue by Tsurumaki-Kokoro** [yaowan233/nonebot-plugin-osubot#48]
03-11 13:34:37 [ERROR] nonebot | Failed to import "nonebot_plugin_osubot"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\UserData\Bots\osubot\osubot-py312\.venv\Lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\UserData\Bots\osubot\osubot-py312\.venv\Lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\UserData\Bots\osubot\osubot-py312\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "C:\UserData\Bots\osubot\osubot-py312\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\UserData\Bots\osubot\osubot-py312\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\UserData\Bots\osubot\osubot-py312\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\UserData\Bots\osubot\osubot-py312\.venv\Lib\site-packages\nonebot_plugin_osubot\__init__.py", line 14, in <module>
    from .matcher import *
  File "C:\UserData\Bots\osubot\osubot-py312\.venv\Lib\site-packages\nonebot_plugin_osubot\matcher\__init__.py", line 17, in <module>
    from .update import update_info, update_pic, clear_background
  File "C:\UserData\Bots\osubot\osubot-py312\.venv\Lib\site-packages\nonebot_plugin_osubot\matcher\update.py", line 15, in <module>
    Alconna(
  File "C:\UserData\Bots\osubot\osubot-py312\.venv\Lib\site-packages\arclet\alconna\core.py", line 171, in __init__
    command_manager.register(self)
  File "C:\UserData\Bots\osubot\osubot-py312\.venv\Lib\site-packages\arclet\alconna\manager.py", line 116, in register
    argv = self.__argv[command] = __argv_type__.get()(command.meta, command.namespace_config, command.separators)  # type: ignore
  File "<string>", line 14, in __init__
TypeError: MessageArgv.__post_init__() takes 1 positional argument but 2 were given

**Comment by yaowan233** [comment]
请提供环境的nonebot-plugin-osubot版本及arclet-alconna版本

**Comment by Tsurumaki-Kokoro** [comment]
nonebot_plugin_osubot 版本为5.2.1
nonebot_plugin_alconna 版本为0.38.2

**Comment by yaowan233** [comment]
将arclet-alconna版本回退到1.8.3版本可以解决
pip install arclet-alconna==1.8.3

**Comment by Tsurumaki-Kokoro** [comment]
感谢，已解决
