### ISSUE TITLE
使用“推荐”功能时报错

### ISSUE THREAD

**Issue by Kayaneru** [yaowan233/nonebot-plugin-osubot#75]
错误日志如下，不知道需要提供哪些信息，有需要的我再补充（新部署的最新版nonebot2，osu插件是使用nb-cli安装的）
```
11-13 09:16:14 [SUCCESS] nonebot | OneBot V11 xxxx | [message.group.normal]: Message xxxx from xxxx@[群:xxxx] '/推荐'
11-13 09:16:14 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_osubot.matcher.recommend, lineno=14)
11-13 09:16:17 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_osubot.matcher.recommend, lineno=14) running complete
11-13 09:16:17 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_osubot.matcher.recommend, lineno=14) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/NoneBot/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/NoneBot/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/root/NoneBot/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/NoneBot/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/NoneBot/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/NoneBot/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/NoneBot/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/NoneBot/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/NoneBot/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/NoneBot/.venv/lib/python3.10/site-packages/nonebot_plugin_osubot/matcher/recommend.py", line 68, in _
    pic_url, s = await handle_recommend(state, recommend)
  File "/root/NoneBot/.venv/lib/python3.10/site-packages/nonebot_plugin_osubot/matcher/recommend.py", line 45, in handle_recommend
    map_info = await get_sayo_map_info(bid, 1)
  File "/root/NoneBot/.venv/lib/python3.10/site-packages/nonebot_plugin_osubot/api.py", line 176, in get_sayo_map_info
    return SayoBeatmap(**res.json())
  File "/root/NoneBot/.venv/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for SayoBeatmap
data.last_update
  Input should be a valid string [type=string_type, input_value=1574857069, input_type=int]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
data.genre
  Input should be a valid string [type=string_type, input_value=7, input_type=int]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
```

**Comment by yaowan233** [comment]
已修复 更新了再试试？

**Comment by Kayaneru** [comment]
> 已修复 更新了再试试？

感谢，试了下可以了，不过又出现了一个新的错误，使用 /info 命令时
```
11-13 11:26:02 [SUCCESS] nonebot | OneBot V11 xxxx | [message.group.normal]: Message xxxx from xxxx@[群:xxxx] '/info'
11-13 11:26:02 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_osubot.matcher.info, lineno=9)
11-13 11:26:02 [WARNING] nonebot_plugin_osubot | 'coroutine' object is not iterable | Retrying... 1/5
11-13 11:26:02 [WARNING] nonebot_plugin_osubot | 'coroutine' object is not iterable | Retrying... 2/5
11-13 11:26:03 [WARNING] nonebot_plugin_osubot | 'coroutine' object is not iterable | Retrying... 3/5
11-13 11:26:03 [WARNING] nonebot_plugin_osubot | 'coroutine' object is not iterable | Retrying... 4/5
11-13 11:26:03 [WARNING] nonebot_plugin_osubot | 'coroutine' object is not iterable | Retrying... 5/5
11-13 11:26:03 [ERROR] nonebot_plugin_osubot | 多次重试失败，请检查网络连接
11-13 11:26:03 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_osubot.matcher.info, lineno=9) running complete
```

**Comment by yaowan233** [comment]
哦 我铸币了
马上修

**Comment by yaowan233** [comment]
修好了 你再试试

**Comment by Kayaneru** [comment]
> 修好了 你再试试

好了
